before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "systemli/prometheus-etherpad-exporter:{{ .Tag }}"
      - "systemli/prometheus-etherpad-exporter:{{ .Major }}"
      - "systemli/prometheus-etherpad-exporter:{{ .Major }}.{{ .Minor }}"
      - "systemli/prometheus-etherpad-exporter:latest"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
